version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.22
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-83-197-230.compute-1.amazonaws.com
            database: d948g0erorhfrm
            ssl: true
            user: ptzjnmzrcfnpsp
            password: ee457ac880e84c2ab3b8362fd8746fb513a9a355862a51d63324354a6da05b1a
            rawAccess: true
            port: '5432'
            migrations: true